### ISSUE TITLE
Make sync health check show the sync percentage and an ETA

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/bitcoind-wrapper#17]

**Comment by k0gen** [comment]
Good call @chrisguida 
Because blockchain syncing is a time consuming process, why not making it easier for users to display progress on the service page more or less like this
![Screenshot from 2021-11-21 11-47-21](https://user-images.githubusercontent.com/3606313/142776694-cd10a0ae-e979-4368-a780-4ca1f23fa90b.png)

**Comment by chrisguida** [comment]
Most likely what will happen is the top line will say "result: loading" like it does now, and the bottom line will contain the progress and ETA

**Comment by chrisguida** [comment]
Progress added in fcd281534ab0650ee646ac3d0e4d695ee97b1c4e. ETA will be added later.

**Comment by chrisguida** [comment]
#17 added to track ETA portion. Sync progress portion is complete.
